name: at_nautel_snmp
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: {at_client: ^3.0.3, at_onboarding_cli: ^1.0.0, dart_snmp: ^2.0.0, intl: ^0.17.0, mqtt_client: ^9.6.9}
