name: nautel_app
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  at_client_mobile: ^3.0.32
  at_utils: ^3.0.0
  path_provider: ^2.0.5
  flutter_dotenv: ^5.0.2
  at_app_flutter: ^5.0.0
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  pretty_gauge: ^1.0.1
  timer_builder: ^2.0.0
  new_gradient_app_bar: ^0.2.0
  window_manager: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

dependency_overrides:
  at_client_mobile:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk
      path: at_client_mobile
      ref: remove_flutter_keychain
