name: nautel_app
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # at_client_mobile: ^3.0.32
  at_utils: ^3.0.0
  path_provider: ^2.0.5
  flutter_dotenv: ^5.0.2
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  pretty_gauge: ^1.0.1
  timer_builder: ^2.0.0
  new_gradient_app_bar: ^0.2.0
  window_manager: ^0.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  icons_launcher: ^2.0.3
  at_app_flutter: 
    git:
      url: https://github.com/atsign-foundation/at_app.git
      ref: fix-pubspec-sample-apps
      path: packages/at_app_flutter


flutter:
  uses-material-design: true
  assets:
    - .env

dependency_overrides:
  at_client_mobile:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      ref: hotfix/window-limit-data-length
      path: at_client_mobile


icons_launcher:
  image_path: 'assets/nautel_icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true 
    linux:
      enable: true

 